AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: VideoCorso Platform - Complete Serverless Backend

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  StripeSecretKey:
    Type: String
    NoEcho: true
    Description: Stripe Secret Key

  StripeWebhookSecret:
    Type: String
    NoEcho: true
    Description: Stripe Webhook Secret

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        COURSES_TABLE: !Ref CoursesTable
        CHAPTERS_TABLE: !Ref ChaptersTable
        LESSONS_TABLE: !Ref LessonsTable
        PURCHASES_TABLE: !Ref PurchasesTable
        PROGRESS_TABLE: !Ref ProgressTable
        USERS_TABLE: !Ref UsersTable
        VIDEO_BUCKET: !Ref VideoBucket
        STRIPE_SECRET_KEY: !Ref StripeSecretKey
        STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
  
Resources:
  # ==================== DynamoDB Tables ====================
  
  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-courses'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: course_id
          AttributeType: S
      KeySchema:
        - AttributeName: course_id
          KeyType: HASH

  ChaptersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-chapters'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chapter_id
          AttributeType: S
        - AttributeName: course_id
          AttributeType: S
      KeySchema:
        - AttributeName: chapter_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CourseIndex
          KeySchema:
            - AttributeName: course_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  LessonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-lessons'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: lesson_id
          AttributeType: S
        - AttributeName: chapter_id
          AttributeType: S
      KeySchema:
        - AttributeName: lesson_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ChapterIndex
          KeySchema:
            - AttributeName: chapter_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PurchasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-purchases'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: purchase_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: purchase_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-progress'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: progress_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: lesson_id
          AttributeType: S
      KeySchema:
        - AttributeName: progress_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: LessonIndex
          KeySchema:
            - AttributeName: lesson_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-videocorso-users'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  # ==================== S3 Buckets ====================
  
  VideoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-videocorso-content'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-videocorso-thumbnails'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false

  # ==================== Cognito User Pool ====================
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-videocorso-users'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
        - Name: full_name
          AttributeDataType: String
          Mutable: true
        - Name: subscription_status
          AttributeDataType: String
          Mutable: true
        - Name: sub_end_date
          AttributeDataType: String
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${Environment}-videocorso-web-client'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref UserPool
      Description: Administrator group

  StudentsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: students
      UserPoolId: !Ref UserPool
      Description: Students group

  # ==================== API Gateway ====================

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${Environment}-videocorso-api'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        DefaultAuthorizer: CognitoAuthorizer

  # ==================== Lambda Functions ====================

  PaymentHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-videocorso-payment-handler'
      CodeUri: ../lambda/payment_handler/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PurchasesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
                - cognito-idp:AdminAddUserToGroup
              Resource: !GetAtt UserPool.Arn
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        CreateCheckout:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /payment/create-checkout
            Method: POST
            Auth:
              Authorizer: NONE
        StripeWebhook:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /payment/webhook
            Method: POST
            Auth:
              Authorizer: NONE

  CourseHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-videocorso-course-handler'
      CodeUri: ../lambda/course_handler/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ChaptersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref LessonsTable
      Events:
        GetCourseStructure:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /course/structure
            Method: GET
        GetFreePreviews:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /course/previews
            Method: GET
            Auth:
              Authorizer: NONE

  VideoHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-videocorso-video-handler'
      CodeUri: ../lambda/video_handler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          CLOUDFRONT_DOMAIN: !GetAtt CloudFrontDistribution.DomainName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref VideoBucket
        - DynamoDBReadPolicy:
            TableName: !Ref LessonsTable
      Events:
        GetVideoUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /course/video/{lesson_id}
            Method: GET

  ProgressHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-videocorso-progress-handler'
      CodeUri: ../lambda/progress_handler/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProgressTable
        - DynamoDBReadPolicy:
            TableName: !Ref PurchasesTable
        - DynamoDBReadPolicy:
            TableName: !Ref LessonsTable
      Events:
        UpdateProgress:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /progress/update
            Method: POST
        GetUserProgress:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /progress/user
            Method: GET
        GetLessonProgress:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /progress/lesson/{lessonId}
            Method: GET
        MarkLessonComplete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /progress/complete
            Method: POST
        GetSubscription:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/subscription
            Method: GET

  AdminHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-videocorso-admin-handler'
      CodeUri: ../lambda/admin_handler/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ChaptersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref LessonsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PurchasesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProgressTable
        - S3CrudPolicy:
            BucketName: !Ref VideoBucket
        - S3CrudPolicy:
            BucketName: !Ref ThumbnailBucket
      Events:
        CreateChapter:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/chapter
            Method: POST
        CreateLesson:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/lesson
            Method: POST
        GetStats:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/stats
            Method: GET
        GetStudents:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/students
            Method: GET
        UploadVideo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/video/upload
            Method: POST
        DeleteVideo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/video/{videoId}
            Method: DELETE
        UpdateChapter:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/chapter/{chapterId}
            Method: PUT
        DeleteChapter:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/chapter/{chapterId}
            Method: DELETE
        UpdateLesson:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/lesson/{lessonId}
            Method: PUT
        DeleteLesson:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/lesson/{lessonId}
            Method: DELETE
        ReorderChapters:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/reorder-chapters
            Method: PUT
        ReorderLessons:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/course/reorder-lessons
            Method: PUT
        UpdateStudent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/student/{studentId}
            Method: PATCH
        SearchStudents:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/students/search
            Method: GET
        GenerateThumbnail:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /admin/video/thumbnail
            Method: POST

  # ==================== CloudFront ====================
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: VideoBucketOrigin
            DomainName: !GetAtt VideoBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: VideoBucketOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TrustedSigners:
            - self
        PriceClass: PriceClass_100

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${Environment}-videocorso'

  VideoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VideoBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: !Sub '${VideoBucket.Arn}/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${Environment}-ApiEndpoint'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${Environment}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${Environment}-UserPoolClientId'

  CloudFrontDomain:
    Description: CloudFront Distribution Domain
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${Environment}-CloudFrontDomain'